#!/usr/bin/env python3
"""Phase 02 — apply Ansible playbooks against the lab VM.

Usage:

    python3 scripts/lab/02_apply.py                       # run the default chain
    python3 scripts/lab/02_apply.py bootstrap             # one playbook
    python3 scripts/lab/02_apply.py bootstrap ssh-hardening
    python3 scripts/lab/02_apply.py zfs -e topology=mirror

This script:
  1. Generates an Ansible inventory file pointing at 127.0.0.1:<ssh_port>
     with the user/credentials from the lab config.
  2. Pushes your public SSH key (if not already authorized) so subsequent
     plays use key auth, not the install-time password.
  3. Invokes ansible-playbook for each playbook in order.

Default chain: bootstrap -> ssh-hardening -> ufw

The chain is conservative on purpose; run zfs.yml, docker.yml, etc.
explicitly when you want to exercise those.
"""

from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
from pathlib import Path

# allow direct invocation
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lab import _ssh, _state  # noqa: E402
from lab._config import load_config  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("lab.apply")

ANSIBLE_DIR = Path(__file__).resolve().parent / "ansible"
INVENTORY_PATH = ANSIBLE_DIR / "inventory.generated.yml"

DEFAULT_PLAYBOOKS = ("bootstrap", "ssh-hardening", "ufw")
KNOWN_PLAYBOOKS = ("bootstrap", "ssh-hardening", "ufw", "zfs", "docker", "services")


def require_ansible() -> None:
    if shutil.which("ansible-playbook") is None:
        raise SystemExit(
            "ansible-playbook not found on PATH.\n"
            "Install: brew install ansible  (macOS)  /  pipx install ansible  (any host)"
        )


def write_inventory(cfg) -> None:
    """Write a static inventory file that points at the lab VM."""
    content = f"""\
# Auto-generated by scripts/lab/02_apply.py — do not edit by hand.
all:
  children:
    lab:
      hosts:
        {cfg.vm_name}:
          ansible_host: {cfg.ssh_host}
          ansible_port: {cfg.ssh_forward_port}
          ansible_user: {cfg.vm_user}
          ansible_become: true
          ansible_become_password: '{cfg.vm_password}'
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_extra_args: >-
            -o StrictHostKeyChecking=accept-new
            -o UserKnownHostsFile=/dev/null
            -o LogLevel=ERROR
"""
    INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_PATH.write_text(content)
    log.info("wrote inventory: %s", INVENTORY_PATH)


def ensure_authorized_key(cfg) -> None:
    """Push the user's SSH public key into the VM's authorized_keys."""
    if not cfg.ssh_public_key_path.exists():
        log.warning(
            "SSH public key not found at %s — Ansible will fall back to password auth.",
            cfg.ssh_public_key_path,
        )
        return
    try:
        _ssh.push_authorized_key(
            cfg.vm_user,
            cfg.ssh_host,
            cfg.ssh_forward_port,
            password=cfg.vm_password,
            public_key_path=cfg.ssh_public_key_path,
        )
    except FileNotFoundError as e:
        log.warning("skipping key push: %s", e)
    except RuntimeError as e:
        log.warning("could not push key automatically: %s", e)
        log.warning("Continuing — Ansible will use password auth this run.")


def run_playbook(name: str, extra_args: list[str]) -> None:
    playbook = ANSIBLE_DIR / "playbooks" / f"{name}.yml"
    if not playbook.exists():
        raise SystemExit(f"playbook not found: {playbook}")
    cmd = [
        "ansible-playbook",
        "-i", str(INVENTORY_PATH),
        str(playbook),
        *extra_args,
    ]
    log.info("running %s", " ".join(cmd))
    env_msg = "(set ANSIBLE_HOST_KEY_CHECKING=False if you hit host-key warnings)"
    log.debug("env hint: %s", env_msg)
    subprocess.run(cmd, check=True, cwd=str(ANSIBLE_DIR))


def parse_args(argv: list[str]) -> tuple[list[str], list[str]]:
    """Split positional playbook names from passthrough ansible args.

    Anything starting with '-' is forwarded to ansible-playbook untouched.
    """
    playbooks: list[str] = []
    extras: list[str] = []
    rest = list(argv)
    while rest:
        arg = rest.pop(0)
        if arg.startswith("-"):
            extras.append(arg)
            # most ansible flags take a value
            if rest and not rest[0].startswith("-") and arg in (
                "-e", "--extra-vars", "-t", "--tags",
                "--skip-tags", "-l", "--limit", "-i", "--inventory",
                "-T", "--timeout",
            ):
                extras.append(rest.pop(0))
        else:
            playbooks.append(arg)
    if not playbooks:
        playbooks = list(DEFAULT_PLAYBOOKS)
    for name in playbooks:
        if name not in KNOWN_PLAYBOOKS:
            raise SystemExit(f"unknown playbook: {name}. Known: {', '.join(KNOWN_PLAYBOOKS)}")
    return playbooks, extras


def main(argv: list[str]) -> None:
    playbooks, extras = parse_args(argv)

    cfg = load_config()
    if not _state.is_phase_done(cfg.state_path, "provision"):
        log.warning(
            "Phase 'provision' has not been marked complete (%s). Run 01_provision.py first.",
            cfg.state_path,
        )

    require_ansible()
    write_inventory(cfg)
    ensure_authorized_key(cfg)

    for name in playbooks:
        run_playbook(name, extras)

    _state.mark_phase_done(cfg.state_path, "apply", playbooks=playbooks)


if __name__ == "__main__":
    main(sys.argv[1:])
