#!/usr/bin/env python3
"""Phase 02 — apply Ansible playbooks against the lab VM.

`run_apply()`:
  1. Generates an Ansible inventory file pointing at 127.0.0.1:<ssh_port>
     with the user/identity from the lab config. Auth is key-based via the
     dedicated lab keypair, which cloud-init already authorised during
     provisioning — no key push happens here.
  2. Invokes ansible-playbook for each requested playbook, in order.
  3. Records the `apply` phase as done in the state file.

Default chain (bare `msai lab apply`): bootstrap -> ssh-hardening -> ufw.
This subset is conservative on purpose. `msai lab all` runs the FULL pipeline
(bootstrap, ssh-hardening, ufw, zfs, docker, services); run those individually
via `msai lab apply <name>` if you want to exercise them one at a time.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

from msai_setup.lab import state
from msai_setup.lab.config import LabConfig, load_config

log = logging.getLogger(__name__)

ANSIBLE_DIR = Path(__file__).resolve().parent / "ansible"
INVENTORY_PATH = ANSIBLE_DIR / "inventory.generated.yml"

DEFAULT_PLAYBOOKS = ("bootstrap", "ssh-hardening", "ufw")
KNOWN_PLAYBOOKS = ("bootstrap", "ssh-hardening", "ufw", "zfs", "docker", "services", "incus", "rdp")


def require_ansible() -> None:
    """Raise SystemExit with install hints if `ansible-playbook` is not on PATH."""
    if shutil.which("ansible-playbook") is None:
        raise SystemExit(
            "ansible-playbook not found on PATH.\n"
            "Install: brew install ansible  (macOS)  /  pipx install ansible  (any host)"
        )


def _vm_endpoint(cfg: LabConfig) -> tuple[str, int]:
    """Return (ansible_host, ansible_port). VirtualBox NAT port-forward."""
    return cfg.ssh_host, cfg.ssh_forward_port


def write_inventory(
    cfg: LabConfig,
    *,
    user: str | None = None,
    become: bool = True,
    path: Path | None = None,
) -> Path:
    """Write a static inventory file that points at the lab VM.

    The lab user has passwordless sudo (cloud-init writes the sudoers drop-in
    during install), so we don't need ansible_become_password. The SSH
    identity is the lab keypair, also already authorised via cloud-init.

    Args:
        cfg: The lab config supplying the SSH endpoint and identity.
        user: SSH user to connect as. Defaults to ``cfg.vm_user``. Pass
            ``"root"`` to target the live installer environment.
        become: Whether Ansible should escalate with ``become``. Set False when
            connecting as root (the live installer session), where there is no
            unprivileged sudo user to escalate from.
        path: Inventory file to write. Defaults to :data:`INVENTORY_PATH`.

    Returns:
        The path the inventory was written to.
    """
    host, port = _vm_endpoint(cfg)
    priv_key = cfg.ssh_public_key_path.with_suffix("")  # strip .pub
    ssh_user = user or cfg.vm_user
    dest = path or INVENTORY_PATH
    content = f"""\
# Auto-generated by msai_setup.lab.apply - do not edit by hand.
all:
  children:
    lab:
      hosts:
        {cfg.vm_name}:
          ansible_host: {host}
          ansible_port: {port}
          ansible_user: {ssh_user}
          ansible_become: {"true" if become else "false"}
          ansible_ssh_private_key_file: {priv_key}
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_extra_args: >-
            -o StrictHostKeyChecking=accept-new
            -o UserKnownHostsFile=/dev/null
            -o IdentitiesOnly=yes
            -o LogLevel=ERROR
"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content)
    log.info("wrote inventory: %s (host=%s port=%d user=%s)", dest, host, port, ssh_user)
    return dest


def run_playbook(name: str, extra_args: list[str], *, inventory: Path | None = None) -> None:
    """Invoke ansible-playbook for the named playbook against the lab inventory."""
    playbook = ANSIBLE_DIR / "playbooks" / f"{name}.yml"
    if not playbook.exists():
        raise SystemExit(f"playbook not found: {playbook}")
    cmd = [
        "ansible-playbook",
        "-i", str(inventory or INVENTORY_PATH),
        str(playbook),
        *extra_args,
    ]
    log.info("running %s", " ".join(cmd))
    env_msg = "(set ANSIBLE_HOST_KEY_CHECKING=False if you hit host-key warnings)"
    log.debug("env hint: %s", env_msg)
    subprocess.run(cmd, check=True, cwd=str(ANSIBLE_DIR))


def run_apply(playbooks: list[str], ansible_args: list[str] | None = None) -> None:
    """Run one or more Ansible playbooks against the lab VM."""
    ansible_args = ansible_args or []
    for name in playbooks:
        if name not in KNOWN_PLAYBOOKS:
            raise ValueError(
                f"unknown playbook: {name}. Known: {', '.join(KNOWN_PLAYBOOKS)}"
            )

    cfg = load_config()
    if not state.is_phase_done(cfg.state_path, "provision"):
        log.warning(
            "Phase 'provision' has not been marked complete (%s). "
            "Create the VM first with `msai create <name>`, or run the full "
            "provision+apply pipeline with `msai lab all`.",
            cfg.state_path,
        )

    require_ansible()
    write_inventory(cfg)

    for name in playbooks:
        run_playbook(name, ansible_args)

    state.mark_phase_done(cfg.state_path, "apply", playbooks=playbooks)
