"""Render a Fedora kickstart (ks.cfg) and build the OEMDRV seed ISO.

Fedora's unattended-install mechanism is **Kickstart**, the analogue of
Ubuntu's Subiquity autoinstall. Anaconda auto-detects a kickstart named
`ks.cfg` in the root of any volume whose filesystem label is exactly
``OEMDRV`` — no kernel argument and no ISO remaster required (unlike the Ubuntu
path, which splices `autoinstall` into GRUB). So the flow is: render a ks.cfg,
pack it into a one-file ISO labelled OEMDRV, and attach that next to the
unmodified Fedora netinst ISO. See docs/incus/fedora-vm.md.

Requires `xorriso` on the control node (`brew install xorriso`).
"""

from __future__ import annotations

import logging
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path

from msai_setup.lab.passwords import sha512_crypt

log = logging.getLogger(__name__)


def render_kickstart(
    *,
    hostname: str,
    user: str,
    full_user_name: str,
    password: str,
    ssh_public_key: str,
    timezone: str = "Europe/Oslo",
    extra_packages: list[str] | None = None,
) -> str:
    """Produce a minimal unattended Fedora kickstart (ks.cfg).

    The install: DHCP networking, locked root, a wheel-group user authorised by
    both an `--iscrypted` SHA-512 password hash and the SSH key, auto-partition
    the disk, install the server environment + openssh-server, and reboot. A
    `%post` grants the user passwordless sudo, mirroring what cloud-init does on
    the Ubuntu side.

    SECURITY: unlike a hand-written ks.cfg with `--plaintext`, the password here
    is a SHA-512 crypt hash (never the plaintext). The generated file is still
    sensitive (it authorises login) and lives only under target/ — do not commit
    a rendered ks.cfg. SSH remains key-based; the password is for console use.
    """
    extras = list(extra_packages or [])
    crypted = sha512_crypt(password)
    key = ssh_public_key.strip()

    # `%packages` lines: a base environment plus openssh-server and any extras.
    package_lines = ["@^server-product-environment", "openssh-server", *extras]
    packages_block = "\n".join(package_lines)

    # Passwordless sudo for the user, written into a sudoers drop-in — the same
    # end state as the Ubuntu late-command.
    sudoers_line = f"{user} ALL=(ALL) NOPASSWD:ALL"

    return f"""\
# Fedora kickstart (ks.cfg) — auto-generated by msai_setup.lab.kickstart.
# Delivered to Anaconda via an OEMDRV-labelled ISO (auto-detected, no boot arg).
lang en_US.UTF-8
keyboard us
timezone {timezone} --utc

# Networking: DHCP on the first link, set the hostname.
network --bootproto=dhcp --device=link --activate --hostname={hostname}

# Accounts: lock root and log in as the wheel-group user. The password is a
# SHA-512 crypt hash (--iscrypted), not plaintext; login is normally by SSH key.
rootpw --lock
user --name={user} --gecos={shlex.quote(full_user_name)} --groups=wheel --iscrypted --password={crypted}
sshkey --username={user} {shlex.quote(key)}

# Disk: wipe and auto-partition the primary disk.
clearpart --all --initlabel
autopart
bootloader --location=mbr

# No first-boot setup agent; reboot into the installed system when done.
firstboot --disable

%packages
{packages_block}
%end

%post --erroronfail
# Passwordless sudo for the lab user (mirrors the Ubuntu cloud-init sudoers).
echo {shlex.quote(sudoers_line)} > /etc/sudoers.d/90-{user}
chmod 0440 /etc/sudoers.d/90-{user}
systemctl enable sshd
%end

reboot
"""


def build_oemdrv_iso(*, kickstart: str, output_path: Path) -> None:
    """Build a one-file ISO labelled OEMDRV containing `kickstart` as `ks.cfg`.

    Anaconda scans attached block devices for a volume labelled OEMDRV and
    auto-runs its `/ks.cfg`. Mirrors cloudinit.build_cidata_iso but with a single
    file and volid=OEMDRV. Uses xorriso so it works on macOS/Linux/Windows alike.
    Idempotent: an existing ISO is overwritten in place.
    """
    if shutil.which("xorriso") is None:
        raise SystemExit(
            "xorriso not found on PATH. Install:\n"
            "    brew install xorriso        # macOS\n"
            "    sudo apt install xorriso     # Linux"
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        staging = Path(td)
        (staging / "ks.cfg").write_text(kickstart)
        cmd = [
            "xorriso", "-as", "mkisofs",
            "-output", str(output_path),
            "-volid", "OEMDRV",
            "-joliet",
            "-rock",
            str(staging / "ks.cfg"),
        ]
        log.info("building OEMDRV ISO at %s", output_path)
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    log.info("OEMDRV ISO ready: %s (%d bytes)", output_path, output_path.stat().st_size)
