"""Render a Windows autounattend.xml and build the UNATTEND seed ISO.

Windows Setup reads an answer file named ``autounattend.xml`` from the root of
any attached removable volume during the WindowsPE phase. So the flow mirrors
the Ubuntu/Fedora seed-ISO approach: render an autounattend.xml, pack it into a
one-file ISO (volume label ``UNATTEND``), and attach it next to the
user-supplied Windows install ISO. See docs/incus/windows-vm.md.

IMPORTANT — differs from the Incus/qemu docs on purpose:

* On VirtualBox the primary disk is **SATA/AHCI (IntelAhci)**, which Windows
  Setup sees natively. There is therefore **NO virtio driver problem** and no
  driver injection — unlike the Incus path, which needs virtio-win. The answer
  file installs straight to disk 0.
* The Windows install ISO is **user-supplied** (licensing): no download, no
  checksum. config.py resolves it from ``$WINDOWS_ISO``.

Honesty: this Mac is Apple Silicon and the target ISOs are x64, so this is NOT
end-to-end runnable here — it is written for an amd64 VBox host and exercised by
unit tests plus the visible-boot hand-off. `processorArchitecture` is amd64.

Requires `xorriso` on the control node (`brew install xorriso`).
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from pathlib import Path
from xml.sax.saxutils import escape

log = logging.getLogger(__name__)

# LabConfig registry keys that skip the Win11 hardware gate (TPM/Secure
# Boot/CPU/RAM). Included as a belt-and-suspenders safety net even though we
# also give the VM a real TPM + Secure Boot, so an unattended install can never
# stall on a hardware-requirement dialog. Order matters for RunSynchronous.
_LABCONFIG_BYPASS = (
    "BypassTPMCheck",
    "BypassSecureBootCheck",
    "BypassCPUCheck",
    "BypassRAMCheck",
)


def _bypass_block() -> str:
    """Render the WindowsPE RunSynchronous LabConfig-bypass commands (win11)."""
    lines = ["      <RunSynchronous>"]
    for order, key in enumerate(_LABCONFIG_BYPASS, start=1):
        cmd = f"reg add HKLM\\SYSTEM\\Setup\\LabConfig /v {key} /t REG_DWORD /d 1 /f"
        lines.append(
            "        <RunSynchronousCommand wcm:action=\"add\">\n"
            f"          <Order>{order}</Order>\n"
            f"          <Path>{escape(cmd)}</Path>\n"
            "        </RunSynchronousCommand>"
        )
    lines.append("      </RunSynchronous>")
    return "\n".join(lines)


def render_autounattend(
    *,
    hostname: str,
    user: str,
    full_user_name: str,
    password: str,
    edition: str,
    product_key: str = "VK7JG-NPHTM-C97JM-9MPGT-3V66T",
    locale: str = "en-US",
    keyboard: str = "en-US",
    bypass_hw_checks: bool = False,
) -> str:
    """Produce a complete Windows autounattend.xml (amd64).

    Does a whole-disk UEFI install to disk 0 (EFI + MSR + primary NTFS), accepts
    the EULA with a generic install product key for the edition, skips the OOBE
    Microsoft-account flow, and creates a local administrator with autologon. For
    Windows 11 (``bypass_hw_checks=True``) it also writes the LabConfig registry
    bypass keys during WindowsPE as a safety net.

    SECURITY: the account password is embedded as ``<PlainText>true</PlainText>``
    (Windows requires it in the answer file) and the product key is literal — the
    same plaintext-secret exposure as a hand-written autounattend.xml. The
    rendered file lives only under target/; do not commit it, and change the
    password after first boot. The key is for installation, not activation.
    """
    # Field values flow into XML text nodes → escape them.
    e_host = escape(hostname)
    e_user = escape(user)
    e_full = escape(full_user_name)
    e_pass = escape(password)
    e_edition = escape(edition)
    e_key = escape(product_key)
    e_locale = escape(locale)
    e_kbd = escape(keyboard)

    bypass = f"\n{_bypass_block()}" if bypass_hw_checks else ""

    return f"""\
<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by msai_setup.lab.windows. Contains a PLAINTEXT password;
     do not commit. VBox primary disk is SATA/AHCI, so no virtio drivers. -->
<unattend xmlns="urn:schemas-microsoft-com:unattend">

  <settings pass="windowsPE">
    <component name="Microsoft-Windows-Setup" processorArchitecture="amd64"
               language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
      <UserData>
        <ProductKey>
          <Key>{e_key}</Key>
        </ProductKey>
        <AcceptEula>true</AcceptEula>
      </UserData>
      <DiskConfiguration>
        <Disk wcm:action="add">
          <DiskID>0</DiskID>
          <WillWipeDisk>true</WillWipeDisk>
          <CreatePartitions>
            <CreatePartition wcm:action="add">
              <Order>1</Order><Type>EFI</Type><Size>260</Size>
            </CreatePartition>
            <CreatePartition wcm:action="add">
              <Order>2</Order><Type>MSR</Type><Size>128</Size>
            </CreatePartition>
            <CreatePartition wcm:action="add">
              <Order>3</Order><Type>Primary</Type><Extend>true</Extend>
            </CreatePartition>
          </CreatePartitions>
          <ModifyPartitions>
            <ModifyPartition wcm:action="add">
              <Order>1</Order><PartitionID>1</PartitionID>
              <Format>FAT32</Format><Label>System</Label>
            </ModifyPartition>
            <ModifyPartition wcm:action="add">
              <Order>2</Order><PartitionID>2</PartitionID>
            </ModifyPartition>
            <ModifyPartition wcm:action="add">
              <Order>3</Order><PartitionID>3</PartitionID>
              <Format>NTFS</Format><Label>Windows</Label><Letter>C</Letter>
            </ModifyPartition>
          </ModifyPartitions>
        </Disk>
      </DiskConfiguration>
      <ImageInstall>
        <OSImage>
          <InstallTo><DiskID>0</DiskID><PartitionID>3</PartitionID></InstallTo>
          <InstallFrom>
            <MetaData wcm:action="add">
              <Key>/IMAGE/NAME</Key><Value>{e_edition}</Value>
            </MetaData>
          </InstallFrom>
        </OSImage>
      </ImageInstall>{bypass}
    </component>
  </settings>

  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
        <ProtectYourPC>3</ProtectYourPC>
      </OOBE>
      <UserAccounts>
        <LocalAccounts>
          <LocalAccount wcm:action="add">
            <Name>{e_user}</Name>
            <DisplayName>{e_full}</DisplayName>
            <Group>Administrators</Group>
            <Password><Value>{e_pass}</Value><PlainText>true</PlainText></Password>
          </LocalAccount>
        </LocalAccounts>
      </UserAccounts>
      <AutoLogon>
        <Enabled>true</Enabled>
        <Username>{e_user}</Username>
        <Password><Value>{e_pass}</Value><PlainText>true</PlainText></Password>
        <LogonCount>1</LogonCount>
      </AutoLogon>
      <ComputerName>{e_host}</ComputerName>
    </component>
  </settings>

  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
      <ComputerName>{e_host}</ComputerName>
    </component>
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64"
               language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
      <InputLocale>{e_kbd}</InputLocale>
      <SystemLocale>{e_locale}</SystemLocale>
      <UILanguage>{e_locale}</UILanguage>
      <UserLocale>{e_locale}</UserLocale>
    </component>
  </settings>

</unattend>
"""


def build_unattend_iso(*, autounattend: str, output_path: Path) -> None:
    """Build a one-file ISO labelled UNATTEND containing `autounattend.xml`.

    Windows Setup scans removable media for ``autounattend.xml`` at the volume
    root. Mirrors kickstart.build_oemdrv_iso but with a single autounattend.xml
    and volid=UNATTEND. Uses xorriso so it works on macOS/Linux/Windows alike.
    Idempotent: an existing ISO is overwritten in place.
    """
    if shutil.which("xorriso") is None:
        raise SystemExit(
            "xorriso not found on PATH. Install:\n"
            "    brew install xorriso        # macOS\n"
            "    sudo apt install xorriso     # Linux"
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        staging = Path(td)
        (staging / "autounattend.xml").write_text(autounattend)
        cmd = [
            "xorriso", "-as", "mkisofs",
            "-output", str(output_path),
            "-volid", "UNATTEND",
            "-joliet",
            "-rock",
            str(staging / "autounattend.xml"),
        ]
        log.info("building UNATTEND ISO at %s", output_path)
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    log.info("UNATTEND ISO ready: %s (%d bytes)", output_path, output_path.stat().st_size)
